# Generated by Django 2.2.6 on 2022-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=50, verbose_name='密码')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('role', models.IntegerField(choices=[(2, '管理员'), (1, '客服'), (0, '会员')], default='1', verbose_name='用户角色')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=50, verbose_name='密码')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('role', models.IntegerField(choices=[(2, '管理员'), (1, '客服'), (0, '会员')], default='2', verbose_name='用户角色')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=50, verbose_name='密码')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('role', models.IntegerField(choices=[(2, '管理员'), (1, '客服'), (0, '会员')], default='0', verbose_name='用户角色')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
