# Generated by Django 2.2.6 on 2022-04-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='created',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='created',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='created',
            new_name='create_time',
        ),
        migrations.AddField(
            model_name='customer',
            name='introduction',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='个人介绍'),
        ),
        migrations.AddField(
            model_name='customer',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='customer',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='manager',
            name='introduction',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='个人介绍'),
        ),
        migrations.AddField(
            model_name='manager',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='manager',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='member',
            name='introduction',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='个人介绍'),
        ),
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='member',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.IntegerField(choices=[(0, '会员'), (1, '客服'), (2, '管理员')], default='1', verbose_name='用户角色'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.IntegerField(choices=[(0, '会员'), (1, '客服'), (2, '管理员')], default='2', verbose_name='用户角色'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.IntegerField(choices=[(0, '会员'), (1, '客服'), (2, '管理员')], default='0', verbose_name='用户角色'),
        ),
    ]
