# Generated by Django 2.2.6 on 2022-04-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220414_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.IntegerField(choices=[(2, '管理员'), (1, '客服'), (0, '会员')], default='1', verbose_name='用户角色'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.IntegerField(choices=[(2, '管理员'), (1, '客服'), (0, '会员')], default='2', verbose_name='用户角色'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.IntegerField(choices=[(2, '管理员'), (1, '客服'), (0, '会员')], default='0', verbose_name='用户角色'),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
