# Generated by Django 2.2.6 on 2022-04-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20220414_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='member',
            name='update_time',
        ),
    ]
