# Generated by Django 3.2.4 on 2022-04-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20220415_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='聊天信息')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_records', to='project.customer', verbose_name='接收者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_records', to='project.member', verbose_name='发送者')),
            ],
            options={
                'verbose_name': '客服聊天记录',
                'verbose_name_plural': '客服聊天记录',
                'db_table': 'tb_chat_records',
            },
        ),
    ]
