# Generated by Django 3.2.4 on 2022-04-19 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_chatrecords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatrecords',
            options={'verbose_name': '会员发给客服的聊天记录', 'verbose_name_plural': '会员发给客服的聊天记录'},
        ),
        migrations.AlterField(
            model_name='chatrecords',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.customer', verbose_name='接收者'),
        ),
        migrations.AlterField(
            model_name='chatrecords',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.member', verbose_name='发送者'),
        ),
        migrations.AlterModelTable(
            name='chatrecords',
            table='chat_records_member_to_customer',
        ),
        migrations.CreateModel(
            name='ChatRecordsCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='聊天信息')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.member', verbose_name='接收者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.customer', verbose_name='发送者')),
            ],
            options={
                'verbose_name': '客服发给会员的聊天记录',
                'verbose_name_plural': '客服发给会员的聊天记录',
                'db_table': 'chat_records_customer_to_member',
            },
        ),
    ]
