# Generated by Django 3.2.4 on 2022-04-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20220419_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='chatrecords',
            name='send_direction',
            field=models.IntegerField(default=0, verbose_name='发送方向'),
        ),
        migrations.AddField(
            model_name='chatrecordscustomer',
            name='send_direction',
            field=models.IntegerField(default=1, verbose_name='发送方向'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.IntegerField(choices=[(2, '管理员'), (1, '客服'), (0, '会员')], default='1', verbose_name='用户角色'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.IntegerField(choices=[(2, '管理员'), (1, '客服'), (0, '会员')], default='2', verbose_name='用户角色'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.IntegerField(choices=[(2, '管理员'), (1, '客服'), (0, '会员')], default='0', verbose_name='用户角色'),
        ),
    ]
